version: '3.8'

services:
  datadrape:
    build: .
    container_name: datadrape-ai
    ports:
      - "5000:5000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - SITE_URL=${SITE_URL:-https://datadrape.com}
      - SITE_NAME=${SITE_NAME:-DataDrape AI}
    volumes:
      - ./temp_uploads:/app/temp_uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional nginx proxy for production
  nginx:
    image: nginx:alpine
    container_name: datadrape-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - datadrape
    restart: unless-stopped
    profiles:
      - production